// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"cs": &dictionary{index: csIndex, data: csData},
		"en": &dictionary{index: enIndex, data: enData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Job ID: %s":                                     1,
	"Job finished with error: %s":                    7,
	"Job finished without errors":                    6,
	"Job of type \"%s\" finished":                    0,
	"Live attributes data extraction and generation": 3,
	"N-grams and query suggestion data generation":   2,
	"Testing and debugging empty job":                4,
	"Unknown job":                                    5,
}

var csIndex = []uint32{ // 9 elements
	0x00000000, 0x00000024, 0x00000035, 0x00000063,
	0x0000008a, 0x000000b1, 0x000000c2, 0x000000dc,
	0x000000fd,
} // Size: 60 bytes

const csData string = "" + // Size: 253 bytes
	"\x02Úloha typu \x22%[1]s\x22 byla dokončena\x02ID úlohy: %[1]s\x02Genero" +
	"vání n-gramů a dat pro našeptávač\x02vygenerování dat pro Live attribute" +
	"s\x02Prázdný testovací a debugovací job\x02Neznámá úloha\x02Úloha skonči" +
	"la bez chyb\x02Úloha skončila s chybou: %[1]s"

var enIndex = []uint32{ // 9 elements
	0x00000000, 0x0000001d, 0x0000002b, 0x00000058,
	0x00000087, 0x000000a7, 0x000000b3, 0x000000cf,
	0x000000ee,
} // Size: 60 bytes

const enData string = "" + // Size: 238 bytes
	"\x02Job of type \x22%[1]s\x22 finished\x02Job ID: %[1]s\x02N-grams and q" +
	"uery suggestion data generation\x02Live attributes data extraction and g" +
	"eneration\x02Testing and debugging empty job\x02Unknown job\x02Job finis" +
	"hed without errors\x02Job finished with error: %[1]s"

	// Total table size 611 bytes (0KiB); checksum: 1EE06547
