// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"cs": &dictionary{index: csIndex, data: csData},
		"en": &dictionary{index: enIndex, data: enData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Job `%s` finished": 0,
	"Job type":          1,
	"Live attributes data extraction and generation": 3,
	"N-grams and query suggestion data generation":   2,
	"Testing and debugging empty job":                4,
	"Unknown job":                                    5,
}

var csIndex = []uint32{ // 7 elements
	0x00000000, 0x0000001f, 0x0000002a, 0x00000058,
	0x0000007f, 0x000000a6, 0x000000b7,
} // Size: 52 bytes

const csData string = "" + // Size: 183 bytes
	"\x02Úloha `%[1]s` byla dokončena\x02Typ úlohy\x02Generování n-gramů a da" +
	"t pro našeptávač\x02vygenerování dat pro Live attributes\x02Prázdný test" +
	"ovací a debugovací job\x02Neznámá úloha"

var enIndex = []uint32{ // 7 elements
	0x00000000, 0x00000015, 0x0000001e, 0x0000004b,
	0x0000007a, 0x0000009a, 0x000000a6,
} // Size: 52 bytes

const enData string = "" + // Size: 166 bytes
	"\x02Job `%[1]s` finished\x02Job type\x02N-grams and query suggestion dat" +
	"a generation\x02Live attributes data extraction and generation\x02Testin" +
	"g and debugging empty job\x02Unknown job"

	// Total table size 453 bytes (0KiB); checksum: 7D0C1079
